#!/usr/bin/env python3
"""
Carefully scoped script to localize Label Studio frontend strings from English to Chinese.
ONLY replaces strings that are clearly UI text, NOT code identifiers or keyboard event keys.
"""
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SAFE translations: Multi-word UI strings that won't conflict with code
SAFE_TRANSLATIONS = [
    # === Navigation & Headers ===
    ('"Data Manager"', '"数据管理"'),
    ("'Data Manager'", "'数据管理'"),
    ('"Cloud Storage"', '"云存储"'),
    ("'Cloud Storage'", "'云存储'"),
    ('"Machine Learning"', '"机器学习"'),
    ("'Machine Learning'", "'机器学习'"),
    ('"Danger Zone"', '"危险区域"'),
    ("'Danger Zone'", "'危险区域'"),
    ('"Labeling Interface"', '"标注界面"'),
    ("'Labeling Interface'", "'标注界面'"),
    ('"Labeling Config"', '"标注配置"'),
    ("'Labeling Config'", "'标注配置'"),
    ('"Annotation History"', '"标注历史"'),
    ("'Annotation History'", "'标注历史'"),
    ('"Ground Truth"', '"真实标注"'),
    ("'Ground Truth'", "'真实标注'"),
    ('"Account Settings"', '"账户设置"'),
    ("'Account Settings'", "'账户设置'"),
    ('"Personal Info"', '"个人信息"'),
    ("'Personal Info'", "'个人信息'"),
    ('"Source Storage"', '"源存储"'),
    ("'Source Storage'", "'源存储'"),
    ('"Target Storage"', '"目标存储"'),
    ("'Target Storage'", "'目标存储'"),
    ('"Storage Type"', '"存储类型"'),
    ("'Storage Type'", "'存储类型'"),
    ('"Machine Learning Model"', '"机器学习模型"'),
    ("'Machine Learning Model'", "'机器学习模型'"),
    ('"Model Version"', '"模型版本"'),
    ("'Model Version'", "'模型版本'"),
    ('"Project Name"', '"项目名称"'),
    ("'Project Name'", "'项目名称'"),
    ('"All Projects"', '"所有项目"'),
    ("'All Projects'", "'所有项目'"),
    ('"My Projects"', '"我的项目"'),
    ("'My Projects'", "'我的项目'"),
    ('"Project Settings"', '"项目设置"'),
    ("'Project Settings'", "'项目设置'"),
    ('"Total Tasks"', '"总任务数"'),
    ("'Total Tasks'", "'总任务数'"),
    ('"All Tasks"', '"所有任务"'),
    ("'All Tasks'", "'所有任务'"),
    ('"Annotation ID"', '"标注ID"'),
    ("'Annotation ID'", "'标注ID'"),
    ('"First Name"', '"名"'),
    ("'First Name'", "'名'"),
    ('"Last Name"', '"姓"'),
    ("'Last Name'", "'姓'"),
    ('"Join Organization"', '"加入组织"'),
    ("'Join Organization'", "'加入组织'"),
    ('"Toggle navigation"', '"切换导航"'),
    ("'Toggle navigation'", "'切换导航'"),
    ('"Terms of Service"', '"服务条款"'),
    ("'Terms of Service'", "'服务条款'"),
    ('"Privacy Policy"', '"隐私政策"'),
    ("'Privacy Policy'", "'隐私政策'"),

    # === Actions (multi-word, safe) ===
    ('"Submit annotation"', '"提交标注"'),
    ("'Submit annotation'", "'提交标注'"),
    ('"Update annotation"', '"更新标注"'),
    ("'Update annotation'", "'更新标注'"),
    ('"Remove annotation"', '"移除标注"'),
    ("'Remove annotation'", "'移除标注'"),
    ('"Create a project"', '"创建项目"'),
    ("'Create a project'", "'创建项目'"),
    ('"Create Project"', '"创建项目"'),
    ("'Create Project'", "'创建项目'"),
    ('"New Project"', '"新建项目"'),
    ("'New Project'", "'新建项目'"),
    ('"Add Storage"', '"添加存储"'),
    ("'Add Storage'", "'添加存储'"),
    ('"Sync Storage"', '"同步存储"'),
    ("'Sync Storage'", "'同步存储'"),
    ('"Add Model"', '"添加模型"'),
    ("'Add Model'", "'添加模型'"),
    ('"Start Training"', '"开始训练"'),
    ("'Start Training'", "'开始训练'"),
    ('"Create a Model"', '"创建模型"'),
    ("'Create a Model'", "'创建模型'"),
    ('"Sign Up"', '"注册"'),
    ("'Sign Up'", "'注册'"),
    ('"Sign In"', '"登录"'),
    ("'Sign In'", "'登录'"),
    ('"Invite members"', '"邀请成员"'),
    ("'Invite members'", "'邀请成员'"),
    ('"View all"', '"查看全部"'),
    ("'View all'", "'查看全部'"),
    ('"Show more"', '"显示更多"'),
    ("'Show more'", "'显示更多'"),
    ('"Copy to clipboard"', '"复制到剪贴板"'),
    ("'Copy to clipboard'", "'复制到剪贴板'"),
    ('"Learn more"', '"了解更多"'),
    ("'Learn more'", "'了解更多'"),
    ('"Read more"', '"阅读更多"'),
    ("'Read more'", "'阅读更多'"),
    ('"Click here"', '"点击这里"'),
    ("'Click here'", "'点击这里'"),
    ('"See all"', '"查看全部"'),
    ("'See all'", "'查看全部'"),
    ('"Go back"', '"返回"'),
    ("'Go back'", "'返回'"),
    ('"Go to"', '"转到"'),
    ("'Go to'", "'转到'"),
    ('"Coming soon"', '"即将推出"'),
    ("'Coming soon'", "'即将推出'"),

    # === Labels/Headings (multi-word, safe) ===
    ('"In Progress"', '"进行中"'),
    ("'In Progress'", "'进行中'"),
    ('"No projects found"', '"未找到项目"'),
    ("'No projects found'", "'未找到项目'"),
    ('"No projects yet"', '"暂无项目"'),
    ("'No projects yet'", "'暂无项目'"),
    ('"No tasks found"', '"未找到任务"'),
    ("'No tasks found'", "'未找到任务'"),
    ('"No items"', '"无项目"'),
    ("'No items'", "'无项目'"),
    ('"No data"', '"无数据"'),
    ("'No data'", "'无数据'"),
    ('"No results"', '"无结果"'),
    ("'No results'", "'无结果'"),
    ('"Not available"', '"不可用"'),
    ("'Not available'", "'不可用'"),
    ('"Something went wrong"', '"出了点问题"'),
    ("'Something went wrong'", "'出了点问题'"),
    ('"An error occurred"', '"发生错误"'),
    ("'An error occurred'", "'发生错误'"),
    ('"Connection refused"', '"连接被拒绝"'),
    ("'Connection refused'", "'连接被拒绝'"),
    ('"Are you sure?"', '"您确定吗？"'),
    ("'Are you sure?'", "'您确定吗？'"),
    ('"Are you sure you want to delete"', '"您确定要删除吗"'),
    ("'Are you sure you want to delete'", "'您确定要删除吗'"),
    ('"Successfully created"', '"创建成功"'),
    ("'Successfully created'", "'创建成功'"),
    ('"Successfully updated"', '"更新成功"'),
    ("'Successfully updated'", "'更新成功'"),
    ('"Successfully deleted"', '"删除成功"'),
    ("'Successfully deleted'", "'删除成功'"),
    ('"Successfully saved"', '"保存成功"'),
    ("'Successfully saved'", "'保存成功'"),
    ('"Please wait"', '"请稍候"'),
    ("'Please wait'", "'请稍候'"),
    ('"Last 7 days"', '"最近7天"'),
    ("'Last 7 days'", "'最近7天'"),
    ('"Last 30 days"', '"最近30天"'),
    ("'Last 30 days'", "'最近30天'"),
    ('"This month"', '"本月"'),
    ("'This month'", "'本月'"),
    ('"Last month"', '"上月"'),
    ("'Last month'", "'上月'"),
    ('"per page"', '"每页"'),
    ("'per page'", "'每页'"),

    # === Single words that are clearly UI-only and safe ===
    # These are commonly used as button labels, titles, etc.
    ('"Projects"', '"项目"'),
    ("'Projects'", "'项目'"),
    ('"Settings"', '"设置"'),
    ("'Settings'", "'设置'"),
    ('"People"', '"人员"'),
    ("'People'", "'人员'"),
    ('"Models"', '"模型"'),
    ("'Models'", "'模型'"),
    ('"Webhooks"', '"网络钩子"'),
    ("'Webhooks'", "'网络钩子'"),
    ('"Annotation"', '"标注"'),
    ("'Annotation'", "'标注'"),
    ('"Annotations"', '"标注"'),
    ("'Annotations'", "'标注'"),
    ('"Storage"', '"存储"'),
    ("'Storage'", "'存储'"),
    ('"Predictions"', '"预测"'),
    ("'Predictions'", "'预测'"),
    ('"Prediction"', '"预测"'),
    ("'Prediction'", "'预测'"),
    ('"General"', '"通用"'),
    ("'General'", "'通用'"),
    ('"Export"', '"导出"'),
    ("'Export'", "'导出'"),
    ('"Import"', '"导入"'),
    ("'Import'", "'导入'"),
    ('"Save"', '"保存"'),
    ("'Save'", "'保存'"),
    ('"Cancel"', '"取消"'),
    ("'Cancel'", "'取消'"),
    ('"Edit"', '"编辑"'),
    ("'Edit'", "'编辑'"),
    ('"Update"', '"更新"'),
    ("'Update'", "'更新'"),
    ('"Copy"', '"复制"'),
    ("'Copy'", "'复制'"),
    ('"Close"', '"关闭"'),
    ("'Close'", "'关闭'"),
    ('"Back"', '"返回"'),
    ("'Back'", "'返回'"),
    ('"Next"', '"下一步"'),
    ("'Next'", "'下一步'"),
    ('"Submit"', '"提交"'),
    ("'Submit'", "'提交'"),
    ('"Confirm"', '"确认"'),
    ("'Confirm'", "'确认'"),
    ('"Search"', '"搜索"'),
    ("'Search'", "'搜索'"),
    ('"Filter"', '"筛选"'),
    ("'Filter'", "'筛选'"),
    ('"Refresh"', '"刷新"'),
    ("'Refresh'", "'刷新'"),
    ('"Download"', '"下载"'),
    ("'Download'", "'下载'"),
    ('"Upload"', '"上传"'),
    ("'Upload'", "'上传'"),
    ('"Add"', '"添加"'),
    ("'Add'", "'添加'"),
    ('"Remove"', '"移除"'),
    ("'Remove'", "'移除'"),
    ('"Reset"', '"重置"'),
    ("'Reset'", "'重置'"),
    ('"Clear"', '"清除"'),
    ("'Clear'", "'清除'"),
    ('"Start"', '"开始"'),
    ("'Start'", "'开始'"),
    ('"Stop"', '"停止"'),
    ("'Stop'", "'停止'"),
    ('"Retry"', '"重试"'),
    ("'Retry'", "'重试'"),
    ('"Skip"', '"跳过"'),
    ("'Skip'", "'跳过'"),
    ('"Finish"', '"完成"'),
    ("'Finish'", "'完成'"),
    ('"Accept"', '"接受"'),
    ("'Accept'", "'接受'"),
    ('"Reject"', '"拒绝"'),
    ("'Reject'", "'拒绝'"),
    ('"Description"', '"描述"'),
    ("'Description'", "'描述'"),
    ('"Title"', '"标题"'),
    ("'Title'", "'标题'"),
    ('"Name"', '"名称"'),
    ("'Name'", "'名称'"),
    ('"Label"', '"标签"'),
    ("'Label'", "'标签'"),
    ('"Color"', '"颜色"'),
    ("'Color'", "'颜色'"),
    ('"Type"', '"类型"'),
    ("'Type'", "'类型'"),
    ('"Status"', '"状态"'),
    ("'Status'", "'状态'"),
    ('"Created"', '"已创建"'),
    ("'Created'", "'已创建'"),
    ('"Updated"', '"已更新"'),
    ("'Updated'", "'已更新'"),
    ('"Actions"', '"操作"'),
    ("'Actions'", "'操作'"),
    ('"Details"', '"详情"'),
    ("'Details'", "'详情'"),
    ('"Tasks"', '"任务"'),
    ("'Tasks'", "'任务'"),
    ('"Task"', '"任务"'),
    ("'Task'", "'任务'"),
    ('"Completed"', '"已完成"'),
    ("'Completed'", "'已完成'"),
    ('"Pending"', '"待处理"'),
    ("'Pending'", "'待处理'"),
    ('"Failed"', '"失败"'),
    ("'Failed'", "'失败'"),
    ('"Queued"', '"排队中"'),
    ("'Queued'", "'排队中'"),
    ('"Accepted"', '"已接受"'),
    ("'Accepted'", "'已接受'"),
    ('"Rejected"', '"已拒绝"'),
    ("'Rejected'", "'已拒绝'"),
    ('"Skipped"', '"已跳过"'),
    ("'Skipped'", "'已跳过'"),
    ('"Submitted"', '"已提交"'),
    ("'Submitted'", "'已提交'"),
    ('"Draft"', '"草稿"'),
    ("'Draft'", "'草稿'"),
    ('"Active"', '"活跃"'),
    ("'Active'", "'活跃'"),
    ('"Disabled"', '"已禁用"'),
    ("'Disabled'", "'已禁用'"),
    ('"Enabled"', '"已启用"'),
    ("'Enabled'", "'已启用'"),
    ('"Labeled"', '"已标注"'),
    ("'Labeled'", "'已标注'"),
    ('"Unlabeled"', '"未标注"'),
    ("'Unlabeled'", "'未标注'"),
    ('"Account"', '"账户"'),
    ("'Account'", "'账户'"),
    ('"Login"', '"登录"'),
    ("'Login'", "'登录'"),
    ('"Logout"', '"退出登录"'),
    ("'Logout'", "'退出登录'"),
    ('"Email"', '"邮箱"'),
    ("'Email'", "'邮箱'"),
    ('"Password"', '"密码"'),
    ("'Password'", "'密码'"),
    ('"Username"', '"用户名"'),
    ("'Username'", "'用户名'"),
    ('"Phone"', '"电话"'),
    ("'Phone'", "'电话'"),
    ('"Profile"', '"个人资料"'),
    ("'Profile'", "'个人资料'"),
    ('"Organization"', '"组织"'),
    ("'Organization'", "'组织'"),
    ('"Members"', '"成员"'),
    ("'Members'", "'成员'"),
    ('"Invite"', '"邀请"'),
    ("'Invite'", "'邀请'"),
    ('"Notifications"', '"通知"'),
    ("'Notifications'", "'通知'"),
    ('"Warning"', '"警告"'),
    ("'Warning'", "'警告'"),
    ('"Error"', '"错误"'),
    ("'Error'", "'错误'"),
    ('"Info"', '"信息"'),
    ("'Info'", "'信息'"),
    ('"Success"', '"成功"'),
    ("'Success'", "'成功'"),
    ('"Debug"', '"调试"'),
    ("'Debug'", "'调试'"),
    ('"Welcome"', '"欢迎"'),
    ("'Welcome'", "'欢迎'"),
    ('"Overview"', '"概览"'),
    ("'Overview'", "'概览'"),
    ('"Configuration"', '"配置"'),
    ("'Configuration'", "'配置'"),
    ('"Documentation"', '"文档"'),
    ("'Documentation'", "'文档'"),
    ('"Support"', '"支持"'),
    ("'Support'", "'支持'"),
    ('"Feedback"', '"反馈"'),
    ("'Feedback'", "'反馈'"),
    ('"About"', '"关于"'),
    ("'About'", "'关于'"),
    ('"Help"', '"帮助"'),
    ("'Help'", "'帮助'"),
    ('"Version"', '"版本"'),
    ("'Version'", "'版本'"),
    ('"Results"', '"结果"'),
    ("'Results'", "'结果'"),
    ('"Total"', '"总计"'),
    ("'Total'", "'总计'"),
    ('"Page"', '"页"'),
    ("'Page'", "'页'"),
    ('"Yes"', '"是"'),
    ("'Yes'", "'是'"),
    ('"No"', '"否"'),
    ("'No'", "'否'"),
    ('"OK"', '"确定"'),
    ("'OK'", "'确定'"),
    ('"Today"', '"今天"'),
    ("'Today'", "'今天'"),
    ('"Yesterday"', '"昨天"'),
    ("'Yesterday'", "'昨天'"),
    ('"Loading"', '"加载中"'),
    ("'Loading'", "'加载中'"),
    ('"Loading…"', '"加载中…"'),
    ("'Loading…'", "'加载中…'"),
    ('"Saving…"', '"保存中…"'),
    ("'Saving…'", "'保存中…'"),
    ('"Deleting…"', '"删除中…"'),
    ("'Deleting…'", "'删除中…'"),
    ('"Copied!"', '"已复制！"'),
    ("'Copied!'", "'已复制！'"),
    ('"Select…"', '"请选择…"'),
    ("'Select…'", "'请选择…'"),
    ('"Select"', '"选择"'),
    ("'Select'", "'选择'"),
    ('"Required"', '"必填"'),
    ("'Required'", "'必填'"),
    ('"Optional"', '"可选"'),
    ("'Optional'", "'可选'"),

    # === Plural/singular pairs (safe context) ===
    ('"Users"', '"用户"'),
    ("'Users'", "'用户'"),
    ('"Projects"', '"项目"'),
    ("'Projects'", "'项目'"),
]

# Files/directories to EXCLUDE (test files, story files, etc.)
EXCLUDE_DIRS = {'node_modules', '__mocks__', '.git', 'dist', 'build'}
EXCLUDE_KEYWORDS = ['test', 'spec', 'stories', '.d.ts']


def should_process(filepath):
    """Check if a file should be processed."""
    filename = os.path.basename(filepath)
    for kw in EXCLUDE_KEYWORDS:
        if kw in filename.lower():
            return False
    return True


def translate_file(filepath):
    """Replace English strings with Chinese in a file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    original = content
    for en, zh in SAFE_TRANSLATIONS:
        if en in content:
            content = content.replace(en, zh)

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False


def main():
    src_dirs = [
        os.path.join(BASE_DIR, 'web', 'apps', 'labelstudio', 'src'),
        os.path.join(BASE_DIR, 'web', 'libs', 'app-common', 'src'),
        os.path.join(BASE_DIR, 'web', 'libs', 'core', 'src'),
        os.path.join(BASE_DIR, 'web', 'libs', 'datamanager', 'src'),
        os.path.join(BASE_DIR, 'web', 'libs', 'editor', 'src'),
        os.path.join(BASE_DIR, 'web', 'libs', 'ui', 'src'),
    ]

    # Also process the datamanager Common components
    extra_dirs = [
        os.path.join(BASE_DIR, 'web', 'libs', 'datamanager', 'src', 'components'),
    ]

    total_files = 0
    modified_files = 0

    for src_dir in src_dirs:
        if not os.path.exists(src_dir):
            print(f"Directory not found: {src_dir}")
            continue

        for root, dirs, files in os.walk(src_dir):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for filename in files:
                if filename.endswith(('.tsx', '.jsx', '.ts', '.js')):
                    filepath = os.path.join(root, filename)
                    if should_process(filepath):
                        total_files += 1
                        if translate_file(filepath):
                            modified_files += 1
                            print(f"  Modified: {os.path.relpath(filepath, BASE_DIR)}")

    print(f"\nProcessed {total_files} files, modified {modified_files} files.")


if __name__ == '__main__':
    main()
